# Required
version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: doc/sphinx/conf.py

python:
  version: 3.6
  install:
    - requirements: doc/sphinx/requirements.txt
